steps:
    - name: node:10.10.0
      entrypoint: npm
      args: ['install']
    - name: node:10.10.0
      entrypoint: npm
      args: ['run', 'build']
    - name: node:10.10.0
      entrypoint: npm
      args: ['run', 'export']
    - name: gcr.io/cloud-builders/gsutil
      args: ['-m', 'rsync', '-r', '-c', '-d', './out', 'gs://agsl']
